### ISSUE TITLE
Support for various DB

### ISSUE THREAD

**Issue by ohaddahan** [HotFusionMan/nativeson#6]
Support `MySQL` , `PostsgreSQL` , 'SQLite`.

**Comment by HotFusionMan** [comment]
We probably need to figure out how to check the version of MySQL, as only versions 5.7.22 and later have built-in JSON generation functions: https://dev.mysql.com/doc/refman/5.7/en/json-function-reference.html . This concern isn't nearly as large for PostgreSQL, because it has had its JSON functions since version 9.2 I think, meaning that it has had them for about 5 years already.

Similarly, we'll need to learn how to detect that SQLite's JSON1 extension is installed and not misbehave when it's not installed.

**Comment by ohaddahan** [comment]
Closing before migration.
